pipeline:
  name: tf_test
  identifier: tf_test
  projectIdentifier: Terraform
  orgIdentifier: default
  stages:
    - stage:
        name: Terraform_Deploy
        identifier: Terraform_Deploy
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TerraformPlan
                  identifier: TerraformPlan
                  spec:
                    provisionerIdentifier: <+input>
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: Terraformgithub
                            gitFetchType: Branch
                            branch: harness_tf
                            folderPath: ./
                          type: Github
                      providerCredential:
                        type: Azure
                        spec:
                          connectorRef: <+input>
                          subscriptionId: <+input>
                      secretManagerRef: harnessSecretManager
                      skipRefreshCommand: false
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: ApprovalForApply
                  identifier: ApprovalForApply
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: TerraformApply
                  name: TerraformApply
                  identifier: TerraformApply
                  spec:
                    provisionerIdentifier: <+input>
                    configuration:
                      type: InheritFromPlan
                  timeout: 10m
              - step:
                  type: HarnessApproval
                  name: ApprovalForDestroy
                  identifier: ApprovalForDestroy
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: TerraformDestroy
                  name: TerraformDestroy_1
                  identifier: TerraformDestroy_1
                  spec:
                    provisionerIdentifier: <+input>
                    configuration:
                      type: InheritFromApply
                  timeout: 10m
        tags: {}
        when:
          pipelineStatus: Success
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  properties:
    ci:
      codebase:
        connectorRef: Terraformgithub
        build: <+input>
        sparseCheckout: []
  notificationRules:
    - name: Terraform_mail
      identifier: Terraform_mail
      pipelineEvents:
        - type: PipelineFailed
        - type: StageFailed
          forStages:
            - AllStages
        - type: StepFailed
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - arvindpdige@gmail.com
      enabled: true
